### ISSUE TITLE
Consuming the package doesn't work

### ISSUE THREAD

**Issue by mfeckie** [stacksjs/bun-plugin-dts-auto#4] opened 2023-08-06 09:56 UTC
### Describe the bug

```
error: Could not resolve: "bun-plugin-dts-auto". Maybe you need to "bun install"?
import dts from 'bun-plugin-dts-auto'
                ^
/Users/experiments/totter/build.ts:1:17 16error: script "build" exited with code 1 (SIGHUP)
```

Errors when trying to consume the plugin

Manually editing `package.json` in `node_modules` to remove this line https://github.com/stacksjs/bun-plugin-dts-auto/blob/main/package.json#L25 seems to resolve the problem

### Reproduction

Reproduction

### System Info

```Shell
  System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 240.33 MB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.asdf/installs/nodejs/18.16.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.6.10 - ~/Library/pnpm/pnpm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 115.0.5790.114
    Edge: 114.0.1823.67
    Safari: 16.6
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/stacksjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/stacksjs/contributing).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisbbreuer** [comment] 2024-02-22 20:41
My bad on the late response here. Been busy working on a Stacks release, and we are now finally in a place to consume this ourselves. And duh, ran into this issue, too.

The problem is that we aren't exporting the src files at the moment. A fix is incoming 💪

**Comment by chrisbbreuer** [comment] 2024-02-23 02:22
v0.3.0 is now released and it resolves this issue https://github.com/stacksjs/bun-plugin-dts-auto/releases/tag/v0.3.0

**Closed by chrisbbreuer** 2024-02-23 02:22 UTC
